### ISSUE TITLE
Fail on error

### ISSUE THREAD

**Issue by jeffastorey** [phinze/vagrant-host-shell#15]
If any of the shell steps fail, it would be nice if the provisioning failed all together rather than just writing to stderr

**Comment by richard-scott** [comment]
yes, I agree. setting an exit code to non-zero would be great too.

**Comment by richard-scott** [comment]
ah, just found that this works:

```
config.vm.provision :host_shell do |host_shell|
  host_shell.abort_on_nonzero = true
  host_shell.inline = 'false'
end
```

Maybe 'abort_on_nonzero' should default to true if its not [set](https://github.com/phinze/vagrant-host-shell/blob/master/lib/vagrant-host-shell/config.rb#L16)?

**Comment by jeffastorey** [comment]
I think it would be logical for true to be the default but that option is exactly what I was looking for here. Closing this issue since it can be addressed with that flag.
